import pickle
from matplotlib.pyplot import *

file = open("par_data.pkl")
time_statics = pickle.load(file)
figure()
hold(True)
plot(time_statics[0, :])
plot(time_statics[1, :])
plot(time_statics[2, :])
plot(time_statics[3, :])
plot(time_statics[4, :])
plot(time_statics[5, :])
plot(time_statics[6, :])
plot(time_statics[7, :])
show()

figure()
hold(True)
plot(time_statics[0,:]/time_statics[0, :])
plot(time_statics[0,:]/time_statics[1, :])
plot(time_statics[0,:]/time_statics[2, :])
plot(time_statics[0,:]/time_statics[3, :])
plot(time_statics[0,:]/time_statics[4, :])
plot(time_statics[0,:]/time_statics[5, :])
plot(time_statics[0,:]/time_statics[6, :])
plot(time_statics[0,:]/time_statics[7, :])
show()
exit()